import {expect,test} from "@playwright/test";
import {mkdirSync,writeFileSync} from "node:fs";
import {join} from "node:path";

const enabled=process.env.BACKSTAGE_LIVE_BROWSER==="1";
test.skip(!enabled,"Opt in with BACKSTAGE_LIVE_BROWSER=1 and server-side OpenAI/Sanity credentials.");

function futureWeekday(offset:number){const date=new Date(new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())+"T12:00:00Z");date.setUTCDate(date.getUTCDate()+offset);while(date.getUTCDay()===0)date.setUTCDate(date.getUTCDate()+1);return date.toISOString().slice(0,10);}

test("live Sanity/OpenAI discovery, follow-up, source link, and research draft",async({page})=>{
  test.setTimeout(120_000);
  const discoveryEvidence:Array<{request:number;recommendations:Array<{venueId:string;city:string;locality:string;historical:boolean;sourceIds:string[];statuses:Record<string,string>}>;reads:Array<{venueId:string;paths:string[];sourceReferenceIds:string[]}>}>=[];
  const submittedBriefs:unknown[]=[];
  page.on("request",request=>{if(request.url().includes("/api/venue-discovery")&&request.method()==="POST"){try{submittedBriefs.push(request.postDataJSON().brief);}catch{/* Assertions below report a missing captured brief. */}}});
  await page.on("response",async response=>{if(response.url().includes("/api/venue-discovery")&&response.request().method()==="POST"){try{const data=await response.json() as {recommendations?:Array<{venueId:string;city:string;locality:string;historical:boolean;sourceReferences:Array<{id:string}>;requirementCoverage:Array<{requirement:string;status:string}>}>;retrievalEvidence?:Array<{venueId:string;entryPaths:string[];sourceReferenceIds:string[]}>};if(response.ok())discoveryEvidence.push({request:discoveryEvidence.length+1,recommendations:(data.recommendations||[]).map(item=>({venueId:item.venueId,city:item.city,locality:item.locality,historical:item.historical,sourceIds:item.sourceReferences.map(source=>source.id),statuses:Object.fromEntries(item.requirementCoverage.map(requirement=>[requirement.requirement,requirement.status]))})),reads:(data.retrievalEvidence||[]).map(item=>({venueId:item.venueId,paths:item.entryPaths,sourceReferenceIds:item.sourceReferenceIds}))});}catch{/* The assertions below report missing or malformed responses. */}}});
  await page.setViewportSize({width:1365,height:900});await page.goto("/venues");await expect(page.getByText("Published Sanity content")).toBeVisible();await expect(page.locator(".venue-card")).toHaveCount(6);await expect(page.getByLabel("Filter by city")).toBeVisible();
  await page.getByLabel("Filter by city").selectOption("Delhi NCR");await expect(page.locator(".venue-card")).toHaveCount(4);await expect(page.locator(".venue-card").filter({hasText:"Ofis Square"})).toHaveCount(2);
  await page.getByLabel("Filter by city").selectOption("Bengaluru");await expect(page.locator(".venue-card")).toHaveCount(2);await page.getByLabel("Filter by city").selectOption("All cities");await page.goto("/organizer");
  await page.getByLabel(/What are you calling it/).fill("Live founder community gathering");await page.getByLabel("City").selectOption({label:"Bengaluru"});await page.getByLabel("Kind of gathering").selectOption({label:"Community meetup"});await page.getByLabel(/Who’s coming/).fill("Bengaluru founders and startup operators");await page.getByLabel(/Event date/).fill(futureWeekday(21));await page.getByLabel(/Expected guests/).fill("24");await page.getByLabel(/Budget for the space/).fill("0");await page.getByLabel("Rooms or areas").fill("Gathering room");await page.getByLabel("Equipment or setup").fill("Projector");await page.getByLabel(/Essential requirements/).fill("Explore pro-bono access and founder eligibility");await page.getByRole("button",{name:"Save event brief"}).click();
  let discovery:Record<string,unknown>|undefined;page.on("response",async response=>{if(response.url().includes("/api/venue-discovery")&&response.request().method()==="POST"&&response.ok()){try{discovery=await response.json() as Record<string,unknown>;}catch{/* Ignore unparsable responses; assertions below fail clearly. */}}});
  await page.getByRole("button",{name:"Find suitable venues"}).click();await expect(page.locator(".recommendation-card").first()).toBeVisible({timeout:45_000});
  const shifu=page.locator(".recommendation-card").filter({hasText:"Shifu Den"});await expect(shifu).toBeVisible();await expect(shifu).toContainText(/founder|community|eligible/i);
  await page.locator("#venue-followup").fill("Please narrow this to what the sources say about pro-bono access for Bengaluru founders, and what eligibility remains unconfirmed.");await page.getByRole("button",{name:"Refine leads"}).click();await expect(shifu).toBeVisible({timeout:45_000});await expect(shifu).toContainText(/founder|community/i);
  const recommendationCount=await page.locator(".recommendation-card").count();
  const sourceLink=shifu.getByRole("link").first();const sourceUrl=await sourceLink.getAttribute("href");expect(sourceUrl).toMatch(/^https:\/\//);const popupWait=page.waitForEvent("popup");await sourceLink.click();const sourcePage=await popupWait;await expect(sourcePage).toHaveURL(sourceUrl!);await sourcePage.close();
  await shifu.getByRole("button",{name:"Prepare application draft"}).click();await expect(page.getByLabel("Potential host")).toHaveValue(/venue-shifu-den-bengaluru$/);await expect(page.getByLabel(/What are you calling it/)).toHaveValue("Live founder community gathering");
  await page.getByLabel("Organizer name").fill("Live browser walkthrough");await page.getByLabel("Email",{exact:true}).fill("walkthrough@example.test");await page.getByLabel(/I have reviewed the brief snapshot/).check();await page.getByRole("button",{name:"Save application draft"}).click();await expect(page.getByRole("status").filter({hasText:"Application draft saved"})).toBeVisible({timeout:30_000});
  const card=page.locator(".application-card").filter({hasText:"Live browser walkthrough"});await expect(card).toContainText("DRAFT ONLY");await expect(card).toContainText(/evidence saved from published Sanity|Evidence saved with the draft/i);await expect(card.getByRole("link").first()).toHaveAttribute("href",sourceUrl!);
  await page.reload();await page.locator("#application-workspace-disclosure > summary").click();const restored=page.locator(".application-card").filter({hasText:"Live browser walkthrough"});await expect(restored).toContainText("DRAFT ONLY");await expect(restored).toContainText("Discovery brief snapshot");await expect(restored).toContainText("Resolved from published Sanity records");await expect(restored.getByRole("link").first()).toHaveAttribute("href",sourceUrl!);
  const verification=discovery?.retrievalEvidence as Array<{venueId:string;entryPaths:string[];sourceReferenceIds:string[]}>|undefined;
  const shifuEvidence=verification?.find((entry)=>entry.venueId==="venue-shifu-den-bengaluru");expect(shifuEvidence&&shifuEvidence.entryPaths.length>0&&shifuEvidence.sourceReferenceIds.length>0).toBeTruthy();
  const output=process.env.PLAYWRIGHT_ARTIFACT_DIR||".playwright-artifacts";mkdirSync(output,{recursive:true});writeFileSync(join(output,"live-context-evidence.json"),JSON.stringify({checkedAt:new Date().toISOString(),knowledgeBaseId:"kbPFAVeDOOjD",city:"Bengaluru",venueId:"venue-shifu-den-bengaluru",entryPaths:shifuEvidence!.entryPaths,sourceReferenceIds:shifuEvidence!.sourceReferenceIds,sourceUrl,recommendationCount},null,2));
  await page.setViewportSize({width:1365,height:900});await page.goto("/organizer");await page.getByLabel("Try an example").selectOption("delhi-hackathon");await page.getByRole("button",{name:"Load example"}).click();await expect(page.getByLabel(/Expected guests/)).toHaveValue("80");await page.getByRole("button",{name:"Find suitable venues"}).click();await expect(page.locator(".recommendation-card").first()).toBeVisible({timeout:45_000});
  const hackathon=page.locator(".recommendation-card");await expect(hackathon.first()).toContainText(/Delhi NCR/);
  await page.locator("#venue-followup").fill("Show only leads whose documented locality is Noida. Keep the 80-person hackathon brief and all requirements unchanged.");await page.getByRole("button",{name:"Refine leads"}).click();await expect(page.locator(".recommendation-card").first()).toBeVisible({timeout:45_000});
  const noidaCards=page.locator(".recommendation-card");await expect(noidaCards.first()).toContainText(/Noida/i);
  await page.locator("#venue-followup").fill("Exclude Noida; show only Gurugram-locality leads. Keep my 80-person hackathon brief and all requirements unchanged.");await page.getByRole("button",{name:"Refine leads"}).click();await expect(page.locator(".recommendation-card").first()).toBeVisible({timeout:45_000});
  await expect.poll(()=>discoveryEvidence.length,{timeout:5_000}).toBe(5);
  expect(submittedBriefs).toHaveLength(5);expect(submittedBriefs[4]).toEqual(submittedBriefs[2]);
  writeFileSync(join(output,"live-agent-matrix-evidence.json"),JSON.stringify({checkedAt:new Date().toISOString(),knowledgeBaseId:"kbPFAVeDOOjD",discoveryRequests:discoveryEvidence},null,2));
  const gurugramCards=page.locator(".recommendation-card");
  const hackathonResult=discoveryEvidence[2]?.recommendations||[];expect(hackathonResult.length).toBeGreaterThan(0);expect(hackathonResult.every(item=>item.city==="Delhi NCR"&&item.sourceIds.length>0)).toBeTruthy();
  const coverage=hackathonResult.flatMap(item=>Object.entries(item.statuses));
  for(const pattern of [/Capacity for 80/i,/breakout/i,/Projector|equipment/i,/Event date .*time/i,/Budget of INR/i])expect(coverage.some(([requirement,status])=>pattern.test(requirement)&&status==="unknown")).toBeTruthy();
  expect(discoveryEvidence[3]?.recommendations.length).toBeGreaterThan(0);expect(discoveryEvidence[3]?.recommendations.every(item=>/Noida/i.test(item.locality))).toBeTruthy();expect(discoveryEvidence[3]?.recommendations.every(item=>!item.historical||item.venueId==="venue-paytm-office-noida")).toBeTruthy();
  expect(discoveryEvidence[4]?.recommendations.length).toBeGreaterThan(0);expect(discoveryEvidence[4]?.recommendations.every(item=>/Gurugram|Gurgaon/i.test(item.locality)&&item.city==="Delhi NCR")).toBeTruthy();expect(discoveryEvidence[4]?.recommendations.some(item=>item.venueId==="venue-ofis-noida-sector-62"||/\bNoida\b/i.test(item.locality))).toBeFalsy();expect(discoveryEvidence[4]?.reads.every(item=>item.paths.every(path=>!path.includes("ofis_square_noida")&&!path.includes("paytm_office_noida")))).toBeTruthy();
  await expect(gurugramCards).toHaveCount(discoveryEvidence[4]!.recommendations.length);await expect(gurugramCards.first().locator(".venue-locality")).toContainText(/Gurugram|Gurgaon/i);await expect(gurugramCards.locator(".venue-locality").filter({hasText:/Noida/i})).toHaveCount(0);
  await expect(page.getByLabel("City")).toHaveValue("Delhi NCR");await expect(page.getByLabel(/Expected guests/)).toHaveValue("80");
  await page.setViewportSize({width:390,height:844});const dimensions=await page.evaluate(()=>({width:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth}));expect(dimensions.scrollWidth).toBeLessThanOrEqual(dimensions.width);await page.screenshot({path:join(output,"live-discovery-mobile.png"),fullPage:true});
});
