import {defineField, defineType} from "sanity";

const sourceRefs = () => defineField({name: "sourceReferences", title: "Source references", type: "array", of: [{type: "reference", to: [{type: "sourceReference"}]}]});

const claimFields = [
  defineField({name: "subject", type: "string", validation: (r) => r.required()}),
  defineField({name: "claim", type: "text", rows: 3, validation: (r) => r.required()}),
  defineField({name: "value", type: "text", rows: 3, validation: (r) => r.required()}),
  defineField({name: "evidenceType", type: "string", options: {list: ["public-documentation", "host-confirmed", "historical-event", "unknown", "conflicting", "demonstration"]}, validation: (r) => r.required()}),
  sourceRefs(),
  defineField({name: "checkedAt", type: "date", validation: (r) => r.required()}),
  defineField({name: "historicalDate", type: "date"}),
  defineField({name: "appliesToSpace", type: "reference", to: [{type: "venueSpace"}]}),
  defineField({name: "layout", type: "string"}),
  defineField({name: "qualification", type: "text", rows: 3}),
];

export const schemaTypes = [
  defineType({name: "sourceReference", title: "Source reference", type: "document", fields: [
    defineField({name: "title", type: "string", validation: (r) => r.required()}),
    defineField({name: "url", type: "url", validation: (r) => r.required().uri({scheme: ["http", "https"]})}),
    defineField({name: "publisher", type: "string"}),
    defineField({name: "sourceType", type: "string", options: {list: ["official-page", "historical-event-listing", "host-confirmation", "other"]}, validation: (r) => r.required()}),
    defineField({name: "checkedAt", type: "date", validation: (r) => r.required()}),
    defineField({name: "reviewNote", type: "text", rows: 3}),
  ]}),
  defineType({name: "hostOrganization", title: "Host organization", type: "document", fields: [
    defineField({name: "name", type: "string", validation: (r) => r.required()}),
    defineField({name: "website", type: "url"}), sourceRefs(),
  ]}),
  defineType({name: "venue", title: "Venue", type: "document", fields: [
    defineField({name: "name", type: "string", validation: (r) => r.required()}),
    defineField({name: "city", type: "string", options: {list: ["Delhi NCR", "Bengaluru"]}, validation: (r) => r.required()}),
    defineField({name: "locality", type: "string"}),
    defineField({name: "summary", type: "text", rows: 4, validation: (r) => r.required()}),
    defineField({name: "hostOrganization", type: "reference", to: [{type: "hostOrganization"}]}),
    defineField({name: "relationshipStatus", type: "string", options: {list: ["research-lead", "host-confirmed", "demonstration"]}, validation: (r) => r.required()}),
    defineField({name: "isDemonstration", type: "boolean", initialValue: false}),
    defineField({name: "knowledgeBaseEligible", type: "boolean", initialValue: true}),
    sourceRefs(),
    defineField({name: "claims", type: "array", of: [{type: "claim"}]}),
    defineField({name: "spaces", type: "array", of: [{type: "reference", to: [{type: "venueSpace"}]}]}),
    defineField({name: "resources", type: "array", of: [{type: "reference", to: [{type: "venueResource"}]}]}),
    defineField({name: "policies", type: "array", of: [{type: "reference", to: [{type: "hostingPolicy"}]}]}),
    defineField({name: "opportunities", type: "array", of: [{type: "reference", to: [{type: "hostingOpportunity"}]}]}),
  ]}),
  defineType({name: "claim", title: "Evidence-backed claim", type: "object", fields: claimFields}),
  defineType({name: "venueSpace", title: "Venue space", type: "document", fields: [
    defineField({name: "name", type: "string", validation: (r) => r.required()}),
    defineField({name: "venue", type: "reference", to: [{type: "venue"}], validation: (r) => r.required()}),
    defineField({name: "spaceType", type: "string"}),
    defineField({name: "summary", type: "text", rows: 3, validation: (r) => r.required()}),
    defineField({name: "layout", type: "string"}),
    defineField({name: "capacity", type: "object", fields: [
      defineField({name: "guestCount", type: "number", validation: (r) => r.required().min(1)}),
      defineField({name: "layout", type: "string", validation: (r) => r.required()}),
      defineField({name: "sourceReferences", title: "Source references", type: "array", of: [{type: "reference", to: [{type: "sourceReference"}]}], validation: (r) => r.required().min(1)}),
      defineField({name: "checkedAt", type: "date", validation: (r) => r.required()}),
    ]}), sourceRefs(),
  ]}),
  defineType({name: "venueResource", title: "Equipment or shared resource", type: "document", fields: [
    defineField({name: "name", type: "string", validation: (r) => r.required()}),
    defineField({name: "venue", type: "reference", to: [{type: "venue"}], validation: (r) => r.required()}),
    defineField({name: "resourceType", type: "string"}),
    defineField({name: "summary", type: "text", rows: 3, validation: (r) => r.required()}),
    defineField({name: "availability", type: "string", options: {list: ["documented", "unknown", "conflicting"]}, initialValue: "unknown"}),
    sourceRefs(),
  ]}),
  defineType({name: "hostingPolicy", title: "Hosting policy", type: "document", fields: [
    defineField({name: "title", type: "string", validation: (r) => r.required()}),
    defineField({name: "venue", type: "reference", to: [{type: "venue"}], validation: (r) => r.required()}),
    defineField({name: "statement", type: "text", rows: 3, validation: (r) => r.required()}),
    defineField({name: "evidenceType", type: "string", options: {list: ["public-documentation", "host-confirmed", "unknown", "conflicting"]}, validation: (r) => r.required()}), sourceRefs(),
    defineField({name: "checkedAt", type: "date", validation: (r) => r.required()}),
  ]}),
  defineType({name: "venueContact", title: "Sourced public enquiry route", type: "document", description: "A published route for asking questions. It does not establish availability, capacity, eligibility, or booking authority.", fields: [
    defineField({name: "venues", type: "array", of: [{type: "reference", to: [{type: "venue"}]}], validation: (r) => r.required().min(1).unique()}),
    defineField({name: "type", type: "string", options: {list: ["phone", "email", "enquiry-page"]}, validation: (r) => r.required()}),
    defineField({name: "value", type: "string", description: "E.164 phone number, email address, or the HTTPS enquiry page itself.", validation: (r) => r.required()}),
    defineField({name: "purpose", type: "text", rows: 2, description: "The purpose as published by the source. Do not relabel admissions or support routes as event contacts.", validation: (r) => r.required().max(300)}),
    defineField({name: "scope", type: "string", options: {list: ["venue-specific", "organization-wide"]}, validation: (r) => r.required()}),
    defineField({name: "checkedAt", type: "date", validation: (r) => r.required()}),
    defineField({name: "sourceReferences", title: "Source references", type: "array", of: [{type: "reference", to: [{type: "sourceReference"}]}], validation: (r) => r.required().min(1)}),
  ], preview: {select: {title: "value", subtitle: "purpose"}}}),
  defineType({name: "venuePhoto", title: "Official venue photo", type: "object", description: "Decorative context from an official page. Never evidence of capacity, layout, eligibility, or availability.", fields: [
    defineField({name: "thumbnailUrl", type: "url", description: "HTTPS file on an allowlisted official image host (see scripts/venue-photos.mjs).", validation: (r) => r.required().uri({scheme: ["https"]})}),
    defineField({name: "thumbnailWidth", type: "number", validation: (r) => r.required().integer().positive()}),
    defineField({name: "thumbnailHeight", type: "number", validation: (r) => r.required().integer().positive()}),
    defineField({name: "imageUrl", type: "url", validation: (r) => r.required().uri({scheme: ["https"]})}),
    defineField({name: "width", type: "number", validation: (r) => r.required().integer().positive()}),
    defineField({name: "height", type: "number", validation: (r) => r.required().integer().positive()}),
    defineField({name: "category", type: "string", options: {list: ["event", "event-space", "meeting-space", "workspace", "outdoor-space", "dining", "exterior", "accommodation"]}, validation: (r) => r.required()}),
    defineField({name: "caption", type: "string", description: "Factual; do not infer size, capacity, or current layout.", validation: (r) => r.required().max(300)}),
    defineField({name: "alt", type: "string", validation: (r) => r.required().max(300)}),
    defineField({name: "locationEvidence", type: "string", description: "Why this photo belongs to this venue and branch.", validation: (r) => r.required().max(300)}),
    defineField({name: "credit", type: "string", validation: (r) => r.required()}),
    defineField({name: "reuse", type: "string", description: "Reuse or embedding status. Public availability is not a licence.", validation: (r) => r.required()}),
    defineField({name: "photoDate", type: "date", description: "Only when the source states it."}),
    defineField({name: "sourceReference", type: "reference", to: [{type: "sourceReference"}], validation: (r) => r.required()}),
  ], preview: {select: {title: "caption", subtitle: "category"}}}),
  defineType({name: "venueGallery", title: "Venue photo gallery", type: "document", fields: [
    defineField({name: "venue", type: "reference", to: [{type: "venue"}], validation: (r) => r.required()}),
    defineField({name: "displayPolicy", type: "string", options: {list: ["embed", "link-only"]}, description: "Use link-only when the owner's terms do not allow photos to be shown.", validation: (r) => r.required()}),
    defineField({name: "officialGallerySource", type: "reference", to: [{type: "sourceReference"}]}),
    defineField({name: "rightsNote", type: "text", rows: 2, validation: (r) => r.required()}),
    defineField({name: "checkedAt", type: "date", validation: (r) => r.required()}),
    defineField({name: "photos", type: "array", of: [{type: "venuePhoto"}], validation: (r) => r.max(6)}),
  ], preview: {select: {title: "venue.name", subtitle: "displayPolicy"}}}),
  defineType({name: "hostingOpportunity", title: "Hosting opportunity", type: "document", fields: [
    defineField({name: "title", type: "string", validation: (r) => r.required()}),
    defineField({name: "venue", type: "reference", to: [{type: "venue"}], validation: (r) => r.required()}),
    defineField({name: "summary", type: "text", rows: 3, validation: (r) => r.required()}),
    defineField({name: "preferredEventTypes", type: "array", of: [{type: "string"}]}),
    defineField({name: "accessModel", type: "string", options: {list: ["paid", "sponsored", "pro-bono", "unknown"]}, validation: (r) => r.required()}),
    defineField({name: "fulfillmentModel", type: "string", options: {list: ["instant-booking", "host-approval", "unknown"]}, validation: (r) => r.required()}),
    defineField({name: "availability", type: "string", options: {list: ["documented", "unknown", "conflicting"]}, initialValue: "unknown"}),
    defineField({name: "relationshipStatus", type: "string", options: {list: ["research-lead", "host-confirmed", "demonstration"]}, validation: (r) => r.required()}), sourceRefs(),
  ]}),
];
