"use client";

import {useMemo, useState} from "react";
import type {PublishedVenue} from "@/lib/sanity-venue-data";

export default function VenueCatalog({venues,origin}:{venues:PublishedVenue[];origin:"live"|"preview"}) {
  const [city,setCity]=useState("All cities");
  const visible=useMemo(()=>city==="All cities"?venues:venues.filter((venue)=>venue.city===city),[city,venues]);
  return <main className="venue-page page-wrap">
    <div className="workflow-intro venue-intro"><div className="workflow-heading"><p className="eyebrow"><span className="eyebrow-dot"/> SOURCE-BACKED RESEARCH</p><h1>Places with<br/><em>potential.</em></h1><p>Explore source-linked public information in Delhi NCR and Bengaluru. Each profile keeps unresolved questions visible.</p></div>
      <aside className="venue-origin"><strong>{origin==="live"?"Published Sanity content":"Local research preview"}</strong><span>{origin==="live"?"Fetched at request time from published, eligible research venue records.":"Sanity is not available; this fallback is checked-in research JSON, not a live connection."}</span><span>{venues.length} researched leads · none onboarded for Backstage bookings</span></aside></div>
    <div className="catalog-toolbar"><label htmlFor="city-filter">Filter by city</label><select id="city-filter" value={city} onChange={(event)=>setCity(event.target.value)}><option>All cities</option><option>Delhi NCR</option><option>Bengaluru</option></select><span aria-live="polite">{visible.length} {visible.length===1?"profile":"profiles"}</span></div>
    <div className="venue-grid">{visible.map((venue)=><article className="venue-card" key={venue.id}>
      <div className="venue-card-top"><span className="venue-city">{venue.city}</span><span className="lead-badge">Research lead · not onboarded</span></div><h2>{venue.name}</h2><p className="venue-locality">{venue.locality}</p><p className="venue-summary">{venue.summary}</p>
      {venue.spaces?.length>0&&<section className="venue-section"><h3>Publicly described spaces</h3><ul>{venue.spaces.map((space)=><li key={space.id}><strong>{space.name}</strong><span>{space.summary}</span><small>{space.capacity?`${space.capacity.guestCount} guests · ${space.capacity.layout} · checked ${space.capacity.checkedAt}`:`Capacity and layout: unknown`}</small>{space.sourceReferences?.map((source)=><a key={source.id} href={source.url} target="_blank" rel="noreferrer">Source: {source.title} ↗</a>)}</li>)}</ul></section>}
      {venue.resources?.length>0&&<section className="venue-section"><h3>Facilities mentioned</h3><ul>{venue.resources.map((resource)=><li key={resource.id}><strong>{resource.name}</strong><span>{resource.summary}</span><small>Operational availability: {resource.availability||"unknown"}</small>{resource.sourceReferences?.map((source)=><a key={source.id} href={source.url} target="_blank" rel="noreferrer">Source: {source.title} ↗</a>)}</li>)}</ul></section>}
      <section className="venue-section evidence-section"><h3>What the sources say</h3><ul>{venue.claims.filter((claim)=>claim.evidenceType!=="unknown").map((claim)=><li key={claim.id}><span className="evidence-label">{claim.evidenceType==="historical-event"?`Historical event${claim.historicalDate?` · ${claim.historicalDate}`:""}`:claim.evidenceType==="public-documentation"?"Public documentation":claim.evidenceType}</span><strong>{claim.claim}</strong><span>{claim.value}{claim.qualification?` ${claim.qualification}`:""}</span><small>Source checked {claim.checkedAt||"date not recorded"}</small>{claim.sourceReferences.map((source)=><a key={source.id} href={source.url} target="_blank" rel="noreferrer">Source: {source.title} ↗</a>)}</li>)}</ul></section>
      {venue.claims.some((claim)=>claim.evidenceType==="historical-event")&&<p className="historical-note">Past event evidence does not establish current availability or permission to book through Backstage.</p>}
      <details className="unknowns"><summary>Important unknowns</summary><ul>{venue.claims.filter((claim)=>claim.evidenceType==="unknown"||claim.evidenceType==="conflicting").map((claim)=><li key={claim.id}><strong>{claim.claim}</strong><span>{claim.value}{claim.qualification?` ${claim.qualification}`:""}</span><small>{claim.evidenceType} · checked {claim.checkedAt||"date not recorded"}</small>{claim.sourceReferences.map((source)=><a key={source.id} href={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a>)}</li>)}</ul></details>
      <section className="venue-sources"><h3>Original source references</h3>{venue.sourceReferences.map((source)=><a key={source.id} href={source.url} target="_blank" rel="noreferrer">{source.title}{source.checkedAt?` · checked ${source.checkedAt}`:""} ↗</a>)}</section>
      <p className="venue-disclaimer">A public event mention is not a partnership, live availability, or permission for Backstage to submit a booking.</p>
    </article>)}</div>
  </main>;
}
